# Please look at the .schema.yml for documentation of the values
input:
  path_panel: 'resources/example_panel.csv'
  folders:
    - "resources/example_data"
  file_regexp: ".*\\.zip"

panel:
  path: 'resources/20191128_HubMAP_panel.csv'
  col_metal: 'Metal Tag'
  stacks:
    ilastik:
      col_bool: 'ilastik'
    full:
      col_bool: 'full'



# optional:
ilastik:
  mem_mb: 10000
  threads: 8

cellprofiler:
  container: 'docker://votti/cellprofiler:develop'

varia:
  fn_cell_classifier: 'resources/classifiers/vz_trained_v2.ilp'
  fn_zip_export: 'results/hubmap_processed_v2.zip'
  example_data_urls:
    -
      - '20191203_HuBMAP_Spleen_ED.zip'
      - 'https://polybox.ethz.ch/index.php/s/rcwZEXfk1WwMfjF/download'
#    -
#      - '20191202_HuBMAP_Thymus_ED.zip'
#      - 'https://polybox.ethz.ch/index.php/s/dt3CV99aJjx2NXi/download'
#    -
#      - '20191202_HuBMAP_LympNode_ED.zip'
#      - 'https://polybox.ethz.ch/index.php/s/gPmN61s0RBWf3aP/download'


compensation:
    do_compensation: true
    folder_spillover_slide_acs: 'resources/20191205_huBMAP_compensation2.zip'
    folder_spillover_slide_acs_url: 'https://polybox.ethz.ch/index.php/s/iuQkE8fCMjLwJxa/download'
